### ISSUE TITLE
Recompile required ASAP

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/Polymesh#6]
Move and Rotate by mouse buttons are not working with the current reporitory version. Recompile against the 3.1.0 jar is required ASAP.

That seemed to take care of the problem. See the [Source Forge Discussion](https://sourceforge.net/p/aoi/discussion/47782/thread/b472a1cb10/#5272).

**Comment by Sailsman63** [comment]
From a further post by Klaus, it only helps when he's using Java 8, so we really need to do the proper updates.

We've got a bigger issue, though: right now, none of the currently active AOI team has access to upload new versions of plugins to the repository. I'm working on it, but that may take some time.

**Comment by peteihis** [comment]
>  none of the currently active AOI team has access to upload new versions of plugins to the repository

Oh.

> do the proper updates.

Then it might be reasonable to have PME entirely obey the view manipulation of the core application in future. Now it rotates around the selection, when one is available. It was a good idea from François to do it that way at the time but it still is a kind of a half way solution and not necessary any more. _(I have some times tried to figure out how the code does that, but it seems to be written pretty deep in the structure.)_

**Comment by Sailsman63** [comment]
We released an update, but never closed this issue.
