### ISSUE TITLE
UTF-8 weirdness

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/Polymesh#7]
There seem to be quite a few files with UTF-8 incompatible character coding. The code-base needs to be combed through for those. The cleanup seem en ineffective the way I did it the last time: Select All, Copy, switch to UTF-8, Select All, Paste. 

At least some of the ç-characters are displayed hidden and they become hidden after Paste as well but the compiler still captures the hidden characters.... Probably requires hunting down the non-UTF-8:s manually.

**Comment by Sailsman63** [comment]
I'll take a look. The core application codebase had a few if those, and some others. I had a conversation script that did fairly well, we'll see what it digs up.

**Comment by Sailsman63** [comment]
Resolved by #8
